[project]
name = "support-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymediainfo>=7.0.1",
    "requests>=2.32.5",
]
